#!/bin/bash

# Render デプロイ用スクリプト
# このスクリプトは手動でRenderダッシュボードにコピー＆ペーストする環境変数を出力します

echo "=========================================="
echo "Render MongoDB版デプロイ設定"
echo "=========================================="
echo ""
echo "以下の設定をRenderダッシュボードで使用してください："
echo ""
echo "【基本設定】"
echo "Name: tokyo-wellbeing-map-api-mongo"
echo "Region: Oregon (US West)"
echo "Branch: main"
echo "Root Directory: backend"
echo "Runtime: Python 3"
echo ""
echo "【ビルド設定】"
echo "Build Command: ./render_build_mongo.sh"
echo "Start Command: uvicorn app.main_mongo:app --host 0.0.0.0 --port \$PORT"
echo ""
echo "【環境変数】"
echo "以下の環境変数をコピー＆ペーストしてください："
echo ""
echo "MONGODB_URL:"
echo "mongodb+srv://tokyo-wellbeing-user:AutogenerateSecurePassword@tokyo-wellbeing-cluster.bkavrmq.mongodb.net/tokyo_wellbeing?retryWrites=true&w=majority&appName=tokyo-wellbeing-cluster"
echo ""
echo "PYTHON_VERSION:"
echo "3.11.0"
echo ""
echo "CORS_ORIGINS:"
echo '["https://tokyo-wellbeing-map.vercel.app", "http://localhost:3000"]'
echo ""
echo "ENVIRONMENT:"
echo "production"
echo ""
echo "=========================================="
echo ""
echo "Renderダッシュボード: https://dashboard.render.com"
echo ""
echo "手順："
echo "1. 上記URLにアクセス"
echo "2. New + → Web Service をクリック"
echo "3. tokyo-wellbeing-map リポジトリを選択"
echo "4. 上記の設定を入力"
echo "5. Create Web Service をクリック"
echo ""