#!/bin/bash

echo "=========================================="
echo "Render MongoDB版 修正済み設定"
echo "=========================================="
echo ""
echo "【重要】Build Commandを以下に修正してください："
echo ""
echo "Build Command:"
echo "./render_build_mongo.sh"
echo ""
echo "（注意: 他のコマンドと連結されていないか確認してください）"
echo ""
echo "【その他の設定は変更不要】"
echo "Start Command: uvicorn app.main_mongo:app --host 0.0.0.0 --port \$PORT"
echo ""
echo "=========================================="
echo ""
echo "修正手順："
echo "1. Renderダッシュボード (https://dashboard.render.com) にアクセス"
echo "2. tokyo-wellbeing-map-api-mongo サービスを選択"
echo "3. Settings タブをクリック"
echo "4. Build Command セクションで Edit をクリック"
echo "5. 内容を ./render_build_mongo.sh のみに修正"
echo "6. Save Changes をクリック"
echo "7. Manual Deploy → Deploy latest commit をクリックして再デプロイ"
echo ""